import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.OXFORD_PLAYWRIGHT_MODULE?pathToFileURL(process.env.OXFORD_PLAYWRIGHT_MODULE).href:'playwright');const b=await chromium.launch(),p=await b.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.OXFORD_TEST_URL||'http://127.0.0.1:4174';const state=()=>p.evaluate(()=>JSON.parse(render_game_to_text()));
try{await fs.mkdir('output/boozled',{recursive:true});
 for(const subject of ['english','math'])for(const grade of [7,8]){await p.goto(`${base}/?game=${subject}-${grade}-boozled`);await p.locator('#boozled-edit-questions').click();await p.locator('#team-count').selectOption('3');await p.locator('#boozled-power-count').selectOption('8');await p.locator('#start-game').click();assert.equal((await state()).session.deck.length,14);await p.screenshot({path:'output/boozled/board.png',fullPage:true});let scores=[0,0,0],turn=0;const seen=new Set();
 while((await state()).view!=='result'){
  const before=await state();assert.equal(before.session.turn,turn);await p.locator('[data-mode-action="boozled-pick"]:not([disabled])').first().click();let s=await state(),c=s.session.deck[s.session.active];
  if(c.power){seen.add(c.power);const target=(turn+2)%3;if(await p.locator('#boozled-target').count())await p.locator('#boozled-target').selectOption(String(target));await p.locator('[data-mode-action="boozled-apply"]').click();if(c.power==='swap')[scores[turn],scores[target]]=[scores[target],scores[turn]];if(c.power==='steal'){const amount=Math.min(20,scores[target]);scores[turn]+=amount;scores[target]-=amount;}if(c.power==='lose')scores[turn]=Math.max(0,scores[turn]-20);if(c.power==='gain50')scores[turn]+=50;if(c.power==='enemyLose')scores[target]=Math.max(0,scores[target]-20);await p.screenshot({path:`output/boozled/${c.power}.png`,fullPage:true});
  }else{assert.equal((await state()).modelAnswer,null);await p.locator('[data-mode-action="boozled-reveal"]').click();assert.ok((await state()).modelAnswer);await p.locator('[data-correct="true"]').click();scores[turn]+=15;}
  assert.deepEqual((await state()).session.groups.map(g=>g.score),scores);
  // Stale/double activation cannot apply a question or surprise twice.
  await p.evaluate(()=>handleBoozled({dataset:{modeAction:'boozled-apply'}}));assert.deepEqual((await state()).session.groups.map(g=>g.score),scores);
  await p.locator('[data-mode-action="boozled-next"]').click();turn=(turn+1)%3;
 }
 assert.equal(seen.size,5);assert.equal((await state()).correct,6);assert.equal((await state()).attempts,6);await p.locator('[data-replay]').click();assert.deepEqual((await state()).session.groups.map(g=>g.score),[0,0,0]);assert.equal((await state()).session.used.length,0);
 console.log(`PASS ${subject}-${grade}: full board, all five powers, target selection, score ledger, guards, replay`);
 }
 // Custom model-answer lesson and six-team/no-surprise setup survive export/import.
 await p.goto(`${base}/?game=english-7-boozled`);await p.locator('#boozled-edit-questions').click();await p.locator('#team-count').selectOption('6');await p.locator('#boozled-power-count').selectOption('0');await p.locator('[data-group-name="0"]').fill('Owls');await p.locator('[data-row="0"] [data-field="prompt"]').fill('Our custom question');await p.locator('#save-lesson').click();const pending=p.waitForEvent('download');await p.locator('#download-lesson').click();const d=await pending;await d.saveAs('output/boozled/custom.json');await p.locator('#import-file').setInputFiles('output/boozled/custom.json');assert.equal(await p.locator('#team-count').inputValue(),'6');assert.equal(await p.locator('#boozled-power-count').inputValue(),'0');assert.equal(await p.locator('[data-group-name="0"]').inputValue(),'Owls');await p.locator('#start-game').click();assert.equal((await state()).session.deck.length,6);
 await p.locator('[data-mode-action="boozled-pick"]').first().click();await p.locator('[data-mode-action="boozled-reveal"]').click();await p.locator('[data-correct="false"]').click();assert.ok((await state()).session.groups.every(g=>g.score===0));await p.locator('[data-mode-action="boozled-next"]').click();await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'output/boozled/mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS custom import/export, six teams, zero surprises, wrong answer and mobile');
}finally{await b.close();}
