import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {pathToFileURL} from 'node:url';const {chromium}=await import(pathToFileURL(process.env.OXFORD_PLAYWRIGHT_MODULE).href);const b=await chromium.launch(),p=await b.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.OXFORD_TEST_URL||'http://127.0.0.1:4174';const click=(a,n)=>p.locator('[data-mode-action="pr-'+a+'"]'+(n===undefined?'':'[data-value="'+n+'"]')).first().click();const state=()=>p.evaluate(()=>({s:game.session,index:game.index,items:game.items,done:game.done,correct:game.correct}));async function open(id){await p.goto(base+'/?game='+id);await p.locator('#start-game').click();await p.waitForTimeout(100);}
async function trace(){while((await state()).s.phase==='question'){const z=await state(),pts=z.s.strokes[z.s.stroke];const transformed=await p.locator('#pr-trace').evaluate((el,pts)=>pts.map(([x,y])=>{const v=new DOMPoint(x,y).matrixTransform(el.getScreenCTM());return [v.x,v.y];}),pts);await p.mouse.move(...transformed[0]);await p.mouse.down();for(const pt of transformed.slice(1))await p.mouse.move(...pt);await p.mouse.up();}}
try{await fs.mkdir('output/primary',{recursive:true});await p.goto(base);const packs=await p.evaluate(()=>GAMES.filter(g=>PRIMARY[g.format]).map(g=>({id:g.id,format:g.format})));assert.equal(packs.length,48);assert.equal(await p.evaluate(()=>GAMES.map(validateLesson).length),374);
for(const g of packs){await open(g.id);const over=await p.locator('#arena').evaluate(el=>el.scrollHeight-el.clientHeight);assert.ok(over<=3,g.id+' overflow '+over);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}console.log('PASS all 48 primary packs validate, launch and fit smartboard');
for(const f of await p.evaluate(()=>Object.keys(PRIMARY))){await open(packs.find(g=>g.format===f).id);await p.screenshot({path:'output/primary/'+f+'.png'});let steps=0;while(!(await state()).done&&steps++<100){const {s,items,index}=await state();if(s.phase==='feedback'){await click('next');continue;}
if(f==='blocks'){for(let i=0;i<9;i++)for(let k=0;k<Number(s.values[i]);k++)await click('height',i);await click('check');}
if(f==='shapezones'){const inside=await p.evaluate(()=>prInside(...game.session.dot).sort().join('|'));assert.equal(inside,[...s.values].sort().join('|'));for(const shape of s.values)await click('shape',['circle','square','triangle'].indexOf(shape));await click('check');}
if(f==='fruitsudoku'){for(let i=0;i<9;i++)if(!s.fixed.includes(i)){await click('fruit',s.solution[i]);await click('cell',i);}await click('check');}
if(f==='analogy')await click('analogy',s.options.indexOf('correct'));
if(['pathtrace','numbertrace','lettertrace'].includes(f))await trace();
if(['countpictures','pictureadd'].includes(f))await click('number',s.choices.indexOf(s.values.map(Number).reduce((a,b)=>a+b,0)));
if(f==='missingpicture')await click('piece',s.missing);
if(f==='emotions')await click('feeling',['happy','sad','surprised','angry','worried','sleepy'].indexOf(items[index].answer));
if(f==='symbolgrid'){await p.locator('#pr-number').fill(s.values[s.target]);await p.locator('#pr-number').press('Enter');}
if(f==='symmetrydraw'){for(const point of s.values){const [x,y]=point.split(',').map(Number);await click('dot',y*4+x);}await click('check');}
if(f==='picturestrips'){for(const i of [0,1,2])await click('strip',i);await click('check');}
if(f==='rotatepicture'){for(let i=0;i<4;i++)for(let k=0;k<(Number(s.values[i])-s.turns[i]+4)%4;k++)await click('rotate',i);await click('check');}
if(f==='directions')await click('direction',(s.bottom+s.delta)%4);
}assert.ok((await state()).done,f+' completes');assert.equal((await state()).correct,(await state()).items.length);await p.locator('[data-replay]').click();assert.equal((await state()).done,false);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(80);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),f+' mobile');await p.setViewportSize({width:1366,height:768});console.log('PASS '+f+' completion/replay/mobile');}
assert.deepEqual(errors,[]);}finally{await b.close();}
